version: '3'


services: 
    mysql-development:
        image: mysql:8.0.17
        environment: 
            MYSQL_ROOT_PASSWORD: recruitDB
            MYSQL_DATABASE: recruit
        ports: 
            - "3307:3306"
        expose: 
            - "3307"
        volumes:
            - my-db:/var/lib/mysql

    mongodb_container:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: rootpassword
        ports:
            - 27017:27017
        volumes:
            - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
  my-db: